export const ErrorCode = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  INVALID_MONEY: "INVALID_MONEY",
  INVALID_QUANTITY: "INVALID_QUANTITY",
  INVALID_REFERENCE_MONTH: "INVALID_REFERENCE_MONTH",
  INVALID_CLIENT_NUMBER: "INVALID_CLIENT_NUMBER",
  INVALID_DASHBOARD_QUERY: "INVALID_DASHBOARD_QUERY",
  INVALID_INVOICES_QUERY: "INVALID_INVOICES_QUERY"
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
